#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m -1 &

bspc monitor -d I II III IV V

bspc config border_width         0
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^1'
bspc rule -a Zoom desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a feh state=floating
bspc rule -a kitty state=floating

bspc config focus_follows_pointer true

killall -q dunst
dunst &

$HOME/.config/polybar/launch.sh

picom -b
